sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ahmoud2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahmoud2/react-test npm test


after_success:
  - docker build -t ahmoud2/multi-client ./client
  - docker build -t ahmoud2/multi-nginx ./nginx
  - docker build -t ahmoud2/multi-server ./server
  - docker build -t ahmoud2/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ahmoud2/multi-client
  - docker push ahmoud2/multi-nginx
  - docker push ahmoud2/multi-server
  - docker push ahmoud2/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-144418194253'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
